[global]
developmentMode = false
maxUploadSize = 200

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false
maxRequestSize = 200
baseUrlPath = ""
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#00A86B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "Inter"

[logger]
level = "info"

[runner]
fastReruns = true
enforceSerializableSessionState = false
magicEnabled = false

[client]
caching = true
displayEnabled = true
showErrorDetails = false