# Configuración de secrets para Streamlit Cloud
# Este archivo se usa para configurar variables de entorno en producción

# Clave secreta para la aplicación
SECRET_KEY = "T&U4WO85S$pUOWY03fVHICwGs6^xPezg"

# Clave para tokens JWT
JWT_SECRET_KEY = "mE7#18#Ap$@4yK8r@XpucPM7y@X7ZqBURnjWGrMklF!89IcaXt*f8&i3U$NZzXHI"

# API Key de Groq (reemplazar con tu clave real)
# GROQ_API_KEY = "***GROQ_API_KEY_REMOVED***"

# Configuración adicional (opcional)
DATABASE_URL = "sqlite:///health_analytics.db"
ENABLE_METRICS = true
LOG_LEVEL = "INFO"

# Configuración de email (opcional)
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = 587
# EMAIL_USER = "tu_email@gmail.com"
# EMAIL_PASSWORD = "tu_password_de_aplicacion"

# Configuración de mapas
# MAPBOX_TOKEN = "tu_mapbox_token_aqui"  # Opcional para mapas avanzados