# Configuración de secrets para Streamlit Cloud
# Este archivo se usa para configurar variables de entorno en producción

# API Keys (configurar en Streamlit Cloud)
GROQ_API_KEY = "***GROQ_API_KEY_REMOVED***"

# Configuración de seguridad
SECRET_KEY = "1n]wm<j[DM@^fCRb:4i>6i9Zo3d}^x!s"
JWT_SECRET_KEY = "f%YSzR;h6,WuxNDMn8V`Hg$$?7+j\":,U([3SJ`979>]K3{,(Zu-v!,#Q4E5}#zQV"

# Configuración de base de datos (opcional)
DATABASE_URL = "sqlite:///health_analytics.db"

# Configuración de monitoreo
ENABLE_METRICS = true
LOG_LEVEL = "INFO"

# Configuración de email (opcional)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
EMAIL_USER = "tu_email@gmail.com"
EMAIL_PASSWORD = "tu_password_de_aplicacion"

# Configuración de mapas
MAPBOX_TOKEN = "tu_mapbox_token_aqui"  # Opcional para mapas avanzados