[global]
developmentMode = false
showWarningOnDirectExecution = false


[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
maxUploadSize = 200
maxMessageSize = 200
runOnSave = true
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#059669"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = true

[logger]
level = "info"

[client]
# Forzar layout de escritorio
showSidebarNavigation = true
toolbarMode = "auto"

