[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false
baseUrlPath = ""
runOnSave = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00A86B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#0f172a"
font = "Inter"
base = "light"

[logger]
level = "error"

[runner]
fastReruns = true
enforceSerializableSessionState = false
magicEnabled = false

# NOTA: ui.wideMode y ui.hideSidebarNav fueron removidos en Streamlit 1.30+
# Ahora se usa st.set_page_config(layout="wide") en el código (ver app.py línea ~45)